// <auto-generated />
using System;
using Mentoria.GGR.Lib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mentoria.GGR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mentoria.GGR.Lib.Models.Personagem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEM")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RemovidoEm")
                        .HasColumnType("DATETIME");

                    b.HasKey("ID");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("Mentoria.GGR.Lib.Models.PersonagemHasPoder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEM")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME");

                    b.Property<int>("PersonagemID")
                        .HasColumnType("int");

                    b.Property<int>("PoderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RemovidoEm")
                        .HasColumnType("DATETIME");

                    b.HasKey("ID");

                    b.HasIndex("PersonagemID");

                    b.HasIndex("PoderID");

                    b.ToTable("PersonagemHasPoder");
                });

            modelBuilder.Entity("Mentoria.GGR.Lib.Models.Poder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEM")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Força")
                        .HasColumnType("int");

                    b.Property<string>("Fraqueza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RemovidoEm")
                        .HasColumnType("DATETIME");

                    b.Property<string>("TipoPoder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Poderes");
                });

            modelBuilder.Entity("Mentoria.GGR.Lib.Models.PersonagemHasPoder", b =>
                {
                    b.HasOne("Mentoria.GGR.Lib.Models.Personagem", "Personagem")
                        .WithMany()
                        .HasForeignKey("PersonagemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentoria.GGR.Lib.Models.Poder", "Poder")
                        .WithMany()
                        .HasForeignKey("PoderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");

                    b.Navigation("Poder");
                });
#pragma warning restore 612, 618
        }
    }
}
